import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner"
import Navbar from "@/components/navbar";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <Navbar />
        
        <Toaster />
        {children}
      </body>
    </html>
  );
}